# This is a basic workflow to help you get started with Actions

name: qemu-dl-CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      inputs:
        snapshots:
          description: 'version to download'
          required: true
          default: '20241124'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      SNAPSHOTS_BUILD: ${{ github.event.inputs.snapshots }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: set release date
        shell: bash
        run: |
          echo "RELEASE_DATE=$(date '+%Y-%m-%d-%H-%M-%S')" >> ${GITHUB_ENV}

      # Runs a set of commands using the runners shell
      - name: download qemu
        run: |
          wget https://qemu.weilnetz.de/w64/qemu-w64-setup-${{ github.event.inputs.snapshots }}.exe
          echo test, and deploy your project.

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: qemu-w64-setup-${{ github.event.inputs.snapshots }}
          tag_name: ${{ env.RELEASE_DATE }}
          files: qemu-w64-setup-${{ github.event.inputs.snapshots }}.exe
